server:
  port: 8082
eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zhw:123456@127.0.0.1:8081/eureka/,http://zhw:123456@127.0.0.1:8080/eureka/
security:
  basic:
    enabled: true
  user:
    name: zhw
    password: 123456
spring:
  application:
    name: eureka
